### ISSUE TITLE
Video with id l0GBOoS_Zv4 has a backing instrumental

### ISSUE THREAD

**Issue by erl-j** [JuanFMontesinos/Solos#4]
Check it out:

https://www.youtube.com/watch?v=l0GBOoS_Zv4

Thank you!

**Comment by JuanFMontesinos** [comment]
Hi,
 We are busy until September so I will have a look then. 
Thanks for the feedback.

**Comment by erl-j** [comment]
No worries! Thank you for all your help!

**Comment by JuanFMontesinos** [comment]
Hi,
We have adapted timestamps to remove segments with background noise at 47b17917c8766ff92a2d649b2c031908e3bee338
Added video statistics (mean, std) and precomputed video and audio under request (that can be checked at https://www.juanmontesinos.com/Solos/stamps/)

Thanks for the warning :)
