### ISSUE TITLE
Youtube-dl is down

### ISSUE THREAD

**Issue by sukun1045** [JuanFMontesinos/Solos#5]
Hi, it seems like Youtube-dl is disabled due to a DMCA takedown notice. Are there any other ways or tools I can download the videos? Actually, I may just need the audio stream and body keypoints. Thank you.

**Comment by JuanFMontesinos** [comment]
Hi,
Actually the pip package should be up, right? 
There are many repos and code available for the last version of youtube-dl.
Another option is to check formats available https://www.juanmontesinos.com/Solos/stamps/ 
and request via mail. 

WRT keypoints, https://www.juanmontesinos.com/Solos/python/
As soon as you download the Solos pip package, it should download the skeletons automatically (after instantiating the skeleton reader as shown in the code)
Besides, a direct download link is provided there.

**Comment by sukun1045** [comment]
Thanks for your quick reply. I think I get the latest version of youtube-dl.
![image](https://user-images.githubusercontent.com/22249737/97755036-b7346880-1ab5-11eb-888d-c0c9a44be3c3.png)

But when I run the command:
`python youtubesaver.py from_json /path_to_your_dst`
I get the following problem:
![image](https://user-images.githubusercontent.com/22249737/97754773-53aa3b00-1ab5-11eb-906b-610155078c6e.png)
Do you have any idea what's wrong and how to fix it?

**Comment by JuanFMontesinos** [comment]
Hi,
Seems that indeed it requires a youtube-dl update. So there is nothing to do from my side.
